export enum FeaturesEnum {
  CREATE_POSTS = 'CREATE_POSTS',
  ANSWER_PROTECTED_QUESTIONS = 'ANSWER_PROTECTED_QUESTIONS',
  FLAG_POSTS = 'FLAG_POSTS',
  VOTE_UP = 'VOTE_UP',
  COMMENT = 'COMMENT',
  VOTE_DOWN = 'VOTE_DOWN',
  CREATE_TAGS = 'CREATE_TAGS',
  EDIT_POSTS = 'EDIT_POSTS'
}
